[
  {
    Sequence: 0,
    LogLevel: Information,
    CategoryName: Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests,
    FormattedMessage: An Exception was thrown.,
    Exception: {
      Type: System.ApplicationException,
      Message: Current depth is 5.,
      StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 47
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.VerifyInnerExceptionsAsync() in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 20,
      InnerException: {
        Type: System.ApplicationException,
        Message: Current depth is 4.,
        StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 47
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 43,
        InnerException: {
          Type: System.ApplicationException,
          Message: Current depth is 3.,
          StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 47
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 43,
          InnerException: {
            Type: System.ApplicationException,
            Message: Current depth is 2.,
            StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 47
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 43,
            InnerException: {
              Type: System.ApplicationException,
              Message: Current depth is 1.,
              StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 47
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 43,
              InnerException: {
                Type: System.InvalidOperationException,
                Message: This method throws exceptions!,
                StackTrace:
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 50
   at Stravaig.Extensions.Logging.Diagnostics.Tests.Verify.VerifyLogExceptionTests.ThrowAnExceptionWithInnerExceptions(Int32 depth) in {ProjectDirectory}Verify/VerifyLogExceptionTests.cs:line 43
              }
            }
          }
        }
      }
    }
  }
]